### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tonyyasi** [HectorMg/9g_clone#1]
## Can you update the README please???!

# HELP

**Comment by hectormmg** [comment]
Sure thing buddy, hopefully it’ll be done in the next couple of days! Team’s pretty busy with all the other PRs!

**Comment by tonyyasi** [comment]
Thanks for help, brotha.

Sorri for bad english!!!!!!!

**Comment by hectormmg** [comment]
Nothing about to worry frend!
